version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        #         uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        #        managementApiSecret: popodeperro
        databases:
          default:
            connector: mongo
            host: demonic-one-sdk7x.mongodb.net
            user: azachii_admin
            password: popodeperro
            uri: >-
              mongodb+srv://azachii_admin:popodeperro@cluster0-87br0.gcp.mongodb.net/test?retryWrites=true&w=majority





