version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        #         uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        #        managementApiSecret: popodeperro
        databases:
          default:
            connector: mongo
            uri: mongodb+srv://azachiiStore:popodeperro@cluster0-zt7tq.gcp.mongodb.net/test?retryWrites=true&w=majority





